SET IDENTITY_INSERT [asiakas-taulu]  ON;
INSERT INTO[asiakas-taulu] (asiakasnro, etunimi, sukunimi,sahkoposti,toimitusosoite,postinro, postitoimip)
VALUES 
(1, 'Kati','Rautiainen','kati.rautiainen@sally.fi','Etelдnkatu 4C12','70100','KUOPIO'),
(2, 'Tuomo','Naukkarinen','tuomo.naukkarinen@luukku.com','Hiihtдjдntie 15','70460','KUOPIO'), 
(3, 'Heikki','Vдnskд','heikki.vanska@saky.fi','Keisarinkatu 1','70100','KUOPIO'), 
(4, 'Juhani','Nieminen','juhani.nieminen@luukku.com','Vanginkatu 19','67100','KOKKOLA'), 
(5, 'Risto','Kuusinen','risto.kuusinen@helsinki.fi','Junailijankatu 12','00520','HELSINKI'), 
(6, 'Tuula','Notko','tuula.notko@vaasa.fi','Kellarikatu 8','65100','VAASA'), 
(7, 'Aimo','Vддnдnen','ami@hotmail.com','Backen 1 A','02630','ESPOO'), 
(8, 'Reino','Konttinen','reino.konttinen@helsinki.fi','Malminkatu 36 F','00440','HELSINKI'), 
(9, 'Unto','Honkavaara','unski@luukku.com','Jussilanpiha 2 A','04250','KERAVA'), 
(10, 'Aila','Sipilд','aila.sipila@ibm.fi','Isokuja 5','00200','HELSINKI'), 
(11, 'Eino','Jokinen','eikka@posti.fi','Jokipalstantie 4','05250','KILJAVA'), 
(12, 'Pirjo','Lindroos','pirjo.lindroos@helsinki.fi','Tehtaankatu 18 C 2','00960','HELSINKI'), 
(13, 'Karl','Pailomaa','kalle@sskky.fi','Keulakuja 5','02320','ESPOO'), 
(14, 'Heikki','Lindroos','heikki.lindroos@slk.fi','Vanamonkuja 4 F','05260','HYVINKДД'), 
(15, 'Matias','Laitakari','matias.laitakari@juupati.fi','Hakalantie 2 G','03600','KARKKILA'), 
(16, 'Eero','Sulonen','eero.salonen@rock.fi','Ajomiehentie 2','04300','TUUSULA'), 
(17, 'Pirjo','Kannisto','pirjo.kannisto@luukku.com','Ilmattarenkatu 2','00610','HELSINKI'), 
(18, 'Mauri','Heimo','maukka@yahoo.com','Laivastokatu 4 A','00880','HELSINKI'), 
(19, 'Aune','Hirn','aune.hirn@apu.fi','Torkkelintie 19 C','00110','HELSINKI'), 
(20, 'Heidi','Kaurismдki','heidi.kauris@espoo.fi','Keulakuja 4','02320','ESPOO'), 
(21, 'Tuomo','Kokkonen','tumppi22@sakky.fi','Pohjoiskuja 2 A','00270','HELSINKI'), 
(22, 'Kari','Syrjдnen','kari.syrjanen@klaku.fi','Viertomдki 2','01800','KLAUKKALA'), 
(23, 'Martta','Johansson','martta.johansson@hesa.com','Riistavuorenkatu 4','00300','HELSINKI'), 
(24, 'Onni','Sparre','onni.sparre@ssllkky.fi','Haahkakatu 3 E 15','00570','HELSINKI'), 
(25, 'Stella','Jolkkonen','stella.jolkkonen@ttkky.fi','Viikintie 1 A','02130','ESPOO'), 
(26, 'Kristiina','Hotakainen','kristiina.hotakainen@luukku.com','Kumpuntie 41','06100','PORVOO'), 
(27, 'Eino','Aalto','eno.aalto@vpl.fi','Kaarenjalka 4','03400','VIHTI'), 
(28, 'Heikki','Koskinen','heikki.koskinen@helsinki.fi','Kalevantie 28 C','00530','HELSINKI'), 
(29, 'Terho','Nykдnen','terho.nykanen@riento.com','Ellinkuja 3 A 12','02210','ESPOO'), 
(30, 'Mauri','Mдkelд','mauri.makela@nummela.fi','Kellarikuja 3','03100','NUMMELA'), 
(31, 'Ossi','Reponen','ossi.reponen@tusu.fi','Kotorannankuja 7','04310','TUUSULA'), 
(32, 'Sinikka','Sirkkala','sinikka.sirkkala@pusu.fi','Kotimдentie 2 B','02130','ESPOO'), 
(33, 'Matti','Myllyrinne','matti.myllyrinne@huhu.fi','Vaakatie 3','02340','ESPOO'), 
(34, 'Matias','Mдkelд','matsu@yahoo.com','Laattatie 3 C','02770','ESPOO'), 
(35, 'Hillevi','Sukki','hillevi.sukki@jarvenpaa.fi','Lumikero 6 B','04440','JДRVENPДД'), 
(36, 'Hannu','Eklund','hannu.eklunnd@helsinki.fi','Vallitie 32 B','00510','HELSINKI'), 
(37, 'Lasse','Leminen','lasse.lem@microsoft.com','Kullervonkatu 18C9','00720','HELSINKI'), 
(38, 'Antti','Seppдnen','antti.seppanen@raku.fi','Mannerheimintie 19A2','00100','HELSINKI'), 
(39, 'Harri','Seppдnen','sepu@siilinjarvi.fi','Toritie 8','70800','SIILINJДRVI'), 
(40, 'Laura','Luukkonen','laura.luukkonen@muutto.com','Kivistцnkatu 18','00100','HELSINKI');